# Generated by Django 4.1.3 on 2023-04-13 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Civilservants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('marital_status', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('appointment_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'civilservants',
                'verbose_name_plural': 'civilservants',
            },
        ),
        migrations.CreateModel(
            name='Retirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('appointment_date', models.DateField()),
                ('age', models.IntegerField()),
                ('years_of_work', models.IntegerField()),
                ('retirement_status', models.CharField(max_length=50)),
                ('retiree_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.civilservants')),
            ],
            options={
                'verbose_name': 'retirement',
                'verbose_name_plural': 'retirement',
            },
        ),
        migrations.CreateModel(
            name='csdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=100)),
                ('cs_age', models.IntegerField()),
                ('cs_years', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.civilservants')),
            ],
            options={
                'verbose_name': 'csdetails',
                'verbose_name_plural': 'csdetails',
            },
        ),
    ]
