# Generated by Django 4.1.3 on 2023-04-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilservants',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='civilservants',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
