# Generated by Django 4.1.3 on 2023-04-13 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_civilservants_appointment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept', models.CharField(max_length=100)),
                ('Apt_date', models.DateField()),
                ('Dob', models.DateField()),
                ('Age', models.IntegerField()),
                ('Duration', models.IntegerField()),
                ('Status', models.CharField(max_length=50)),
                ('Retname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.civilservants')),
            ],
            options={
                'verbose_name': 'reports',
                'verbose_name_plural': 'reports',
            },
        ),
    ]
