# Generated by Django 4.1.3 on 2023-04-13 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilservants',
            name='ministry',
            field=models.CharField(default=datetime.datetime(2023, 4, 13, 15, 59, 6, 370893, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csdetails',
            name='minist',
            field=models.CharField(default=datetime.datetime(2023, 4, 13, 15, 59, 14, 442251, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reports',
            name='Minist',
            field=models.CharField(default=datetime.datetime(2023, 4, 13, 15, 59, 23, 32000, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
