# Generated by Django 4.1.3 on 2023-04-14 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_civilservants_ministry_csdetails_minist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retirement',
            name='retiree_department',
            field=models.CharField(default=datetime.datetime(2023, 4, 14, 10, 6, 47, 755470, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retirement',
            name='retiree_ministry',
            field=models.CharField(default=datetime.datetime(2023, 4, 14, 10, 6, 54, 587551, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
