# Generated by Django 4.1.3 on 2023-04-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_retirement_retiree_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='csdetails',
        ),
    ]
