# Generated by Django 4.1.3 on 2023-04-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_delete_csdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='civilservants',
            options={'ordering': ['firstname'], 'verbose_name': 'civilservants', 'verbose_name_plural': 'civilservants'},
        ),
        migrations.AlterModelOptions(
            name='reports',
            options={'ordering': ['-Apt_date'], 'verbose_name': 'reports', 'verbose_name_plural': 'reports'},
        ),
        migrations.AlterModelOptions(
            name='retirement',
            options={'ordering': ['-appointment_date'], 'verbose_name': 'retirement', 'verbose_name_plural': 'retirement'},
        ),
        migrations.AlterField(
            model_name='retirement',
            name='retirement_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
