# Generated by Django 4.1.3 on 2023-04-14 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_civilservants_options_alter_reports_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilservants',
            name='department',
            field=models.CharField(choices=[('', 'Department')], max_length=50),
        ),
        migrations.AlterField(
            model_name='civilservants',
            name='ministry',
            field=models.CharField(choices=[('', 'Ministry')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reports',
            name='Dept',
            field=models.CharField(choices=[('', 'Department')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reports',
            name='Minist',
            field=models.CharField(choices=[('', 'Ministry')], max_length=100),
        ),
        migrations.AlterField(
            model_name='retirement',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(75)]),
        ),
        migrations.AlterField(
            model_name='retirement',
            name='retiree_department',
            field=models.CharField(choices=[('', 'Department')], max_length=100),
        ),
        migrations.AlterField(
            model_name='retirement',
            name='retiree_ministry',
            field=models.CharField(choices=[('', 'Ministry')], max_length=100),
        ),
    ]
