# Generated by Django 4.1.3 on 2023-04-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_civilservants_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilservants',
            name='department',
            field=models.CharField(choices=[('', 'Department'), ('ICT', 'ICT'), ('ICT', 'ICT'), ('ICT', 'ICT'), ('ICT', 'ICT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='civilservants',
            name='ministry',
            field=models.CharField(choices=[('', 'Ministry'), ('Agriculture', 'Agriculture'), ('Agriculture', 'Agriculture'), ('Agriculture', 'Agriculture'), ('Agriculture', 'Agriculture'), ('Agriculture', 'Agriculture')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reports',
            name='Dept',
            field=models.CharField(choices=[('', 'Department'), ('ICT', 'ICT'), ('ICT', 'ICT'), ('ICT', 'ICT'), ('ICT', 'ICT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reports',
            name='Minist',
            field=models.CharField(choices=[('', 'Ministry'), ('Agriculture', 'Agriculture'), ('Agriculture', 'Agriculture'), ('Agriculture', 'Agriculture'), ('Agriculture', 'Agriculture'), ('Agriculture', 'Agriculture')], max_length=100),
        ),
        migrations.AlterField(
            model_name='retirement',
            name='retiree_department',
            field=models.CharField(choices=[('', 'Department'), ('ICT', 'ICT'), ('ICT', 'ICT'), ('ICT', 'ICT'), ('ICT', 'ICT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='retirement',
            name='retiree_ministry',
            field=models.CharField(choices=[('', 'Ministry'), ('Agriculture', 'Agriculture'), ('Agriculture', 'Agriculture'), ('Agriculture', 'Agriculture'), ('Agriculture', 'Agriculture'), ('Agriculture', 'Agriculture')], max_length=100),
        ),
    ]
