# Generated by Django 4.1.3 on 2023-04-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_civilservants_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='Retname',
        ),
        migrations.RemoveField(
            model_name='retirement',
            name='retiree_name',
        ),
        migrations.DeleteModel(
            name='Civilservants',
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
        migrations.DeleteModel(
            name='Retirement',
        ),
    ]
